@startuml
hide circle
skinparam classAttributeIconSize 0

class CreateCategoryView {
}

class CreateCategoryController {
    + createCategory(string code, string description): void
    + saveCreatedCategory(): Result
}

class App {
    - App()
    + {static} getInstance(): App
    + getCategoryContainer(): CategoryContainer
}

class CategoryContainer {
    + create(string code, string description): Category
    + save(Category obj): Result
}

class Category {
    - code
    - description
    Category(string code, string description)
}

CreateCategoryView ..> CreateCategoryController

CreateCategoryController ..> App
CreateCategoryController .> CategoryContainer
CreateCategoryController .> Category

App -> "1" App : instance
App --> "1 " CategoryContainer : maintains

CategoryContainer -> "  * " Category : records
@enduml