project(TasksCore)

add_library(TasksCore headers/domain/model/Category.h sources/domain/model/Category.cpp
        headers/domain/model/CategoryContainer.h sources/domain/model/CategoryContainer.cpp sources/domain/model/Person.cpp headers/domain/model/Person.h sources/domain/shared/StringUtils.cpp headers/domain/shared/StringUtils.h sources/domain/exceptions/TaskDomainError.cpp headers/domain/exceptions/TaskDomainError.h sources/controllers/ui/CreateCategoryController.cpp headers/controllers/ui/CreateCategoryController.h sources/controllers/ui/App.cpp headers/controllers/ui/App.h sources/controllers/ui/AuthController.cpp headers/controllers/ui/AuthController.h sources/controllers/ui/ListCategoriesController.cpp headers/controllers/ui/ListCategoriesController.h sources/controllers/ui/UpdateCategoryController.cpp headers/controllers/ui/UpdateCategoryController.h sources/domain/shared/Result.cpp headers/domain/shared/Result.h sources/controllers/ui/DeleteCategoryController.cpp headers/controllers/ui/DeleteCategoryController.h)