@startuml
autoactivate on
autonumber

actor "System\nAdministrator" as User
participant ":UpdateCategoryView" as View
participant ":UpdateCategoryController" as Ctrl
participant App
participant "app:App" as AppInstance
participant "container:CategoryContainer" as Container
participant "list:List<Category>" as List
participant "cat:Category" as Category

activate User

User -> View: asks to update description of a category

View --> Ctrl** : create()

View -> Ctrl: getAll()

Ctrl -> App: getInstance()
App --> Ctrl: app
Ctrl -> AppInstance: getCategoryContainer()
AppInstance --> Ctrl: container

Ctrl -> Container: getAll()
Container --> Ctrl: list
Ctrl --> View: list
View --> User: shows all existing categories and \n asks to select the one to be updated

User -> View: selects the intended category
View -> View: findSelectedCategory()
View --> View: cat
View -> Category: getDescription()
Category --> View: description
View --> User: shows description of the select category \n and requests the new description

User -> View: types the new description
View -> Category: getCode()
Category --> View: code
View -> Ctrl:updateCategory(code, newDescription)
Ctrl -> Container: findById(code)
Container --> Ctrl: cat
Ctrl -> Category: changeDescription(newDescription)
Category --> Ctrl : ok
Ctrl -> Container: save(cat)
Container --> Ctrl: ok
Ctrl --> View: ok
View --> User: informs operation success
@enduml